### ISSUE TITLE
Simplify spade firmware build process via containerization

### ISSUE THREAD

**Issue by grymmy** [hackclub/spade#18]
There are too many eccentricities to the spade build instructions that make them difficult to complete successfully.  We should set up a simple dockerfile that contains all prerequisites built-in for the build process such that they can be run easily on any platform.  A simple script could be created to "run the build within docker".

**Comment by grymmy** [comment]
This has been invalidated by https://github.com/hackclub/spade/pull/23 I think, closing

**Comment by grymmy** [comment]
Reopening as a HCer has done this! https://hackclub.slack.com/archives/C04T39YERHC/p1704254264113209

**Comment by whatwareweb** [comment]
Hi I've made a docker image to build spade, the repo is available [here](https://github.com/whatwareweb/sprig-docker-build-env). @grymmy suggested to contribute it here, but I'm not really sure where the best place to put it would be (I'm pretty new to large OSS projects like this one)

**Comment by Sheepy3** [comment]
@grymmy should this issue be closed now?

**Comment by whatwareweb** [comment]
I agree this should probably be closed
