### ISSUE TITLE
make it easier to get spade firmware builds

### ISSUE THREAD

**Issue by JosiasAurel** [hackclub/spade#24]
Create a workflow for automatically building spade firmware. 

Thoroughly tested firmware builds will be published to github releases for easy access.

We also need to update links in [sprig UPLOAD.md](https://github.com/hackclub/sprig/blob/main/docs/UPLOAD.md) to point to the latest github release of hackclub/spade.

**Comment by grymmy** [comment]
@JosiasAurel just to be clear - we should not publish the latest builds from main as the officially supported Spade firmware.  Only manually tested / cleared builds should be pointed at end-users - we need to define a process for this.

**Comment by JosiasAurel** [comment]
resolved #23
