### ISSUE TITLE
PC Build crashes when run

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/spade#27]
After compiling a PC build on both Linux (Fedora 38) spade crashes immediately after creating the window with the following error:
```
bouta run some code
engine.js:afterInputs
Fatal glibc error: malloc.c:2593 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
Aborted (core dumped)
```
On MacOS, it also hangs after creating the window (@grymmy), but no logs after `bouta run some code`

**Comment by polypixeldev** [comment]
Managed to get a PC build working after the changes in https://github.com/polypixeldev/spade/commit/ba5cd174d0d7635984717a8e934fd0b54880a008 (tbh, not sure what specifically fixed it though). @grymmy can you see if it fixes it for MacOS as well?

**Comment by JosiasAurel** [comment]
The pc build works fine on MacOS!
